#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#

#
# Copyright 2007 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#

STF_USER_CONFIGURE=
STF_ROOT_CONFIGURE=

STF_ROOT_SETUP=
STF_USER_SETUP=

STF_ROOT_CLEANUP=
STF_USER_CLEANUP=

STF_ROOT_TESTCASES=zfs_acl_chmod_001_pos zfs_acl_mv_001_pos \
	zfs_acl_find_001_pos	zfs_acl_find_002_neg	\
	zfs_acl_pack_001_pos	zfs_acl_cp_003_neg	\
	zfs_acl_cp_002_neg	zfs_acl_cp_001_pos	\
	zfs_acl_ls_001_pos	zfs_acl_ls_002_neg	\
	zfs_acl_pax_001_pos	zfs_acl_pax_002_pos	\
	zfs_acl_pax_003_pos	zfs_acl_pax_004_pos	\
	zfs_acl_pax_005_pos	zfs_acl_pax_006_pos	\
	zfs_acl_tar_001_pos	zfs_acl_tar_002_neg	\
	zfs_acl_compress_001_pos
    

STF_USER_TESTCASES=

STF_ENVFILES=
STF_INCLUDES=

STF_DONTBUILDMODES=true

include $(STF_TOOLS)/Makefiles/Makefile.master
