#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#

#
# Copyright 2009 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#

STF_ROOT_CONFIGURE=
STF_USER_CONFIGURE=

STF_ROOT_SETUP=setup
STF_USER_SETUP=

STF_ROOT_CLEANUP=cleanup
STF_USER_CLEANUP=

STF_ROOT_TESTCASES=userquota_001_pos userquota_002_pos userquota_003_pos \
		   userquota_004_pos userquota_005_neg userquota_006_pos \
		   userquota_007_pos userquota_008_pos userquota_009_pos \
		   userquota_010_pos userquota_011_pos userquota_012_neg \
		   userspace_001_pos userspace_002_pos \
		   groupspace_001_pos groupspace_002_pos


STF_USER_TESTCASES=

STF_ENVFILES=userquota.cfg
STF_INCLUDES=userquota_common.kshlib
STF_DONTBUILDMODES=true

include $(STF_TOOLS)/Makefiles/Makefile.master
