#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#

#
# Copyright 2007 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#

CHECKENV_TARGETS = \
	ce_event_ports \
	ce_filesystem_available\
	ce_gpec \
	ce_ipv6 \
	ce_lwp_interfaces \
	ce_memtest \
	ce_nfs_server \
	ce_number_of_processors \
	ce_number_of_disks \
	ce_platform_type \
	ce_package \
	ce_smf_present \
	ce_tool_exist \
	ce_zones \
	ce_zones_active \
	ce_cmd_in_path \
	ce_file_exist \
	ce_host_reachable \
        ce_config_vars \
        ce_arch_coherence \
        ce_disk_space \
        ce_interface_exist \
        ce_service_available \
	ce_is_system_labeled


include $(CHECKENV_SUITE)/Makefile.com
