#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#

#
# Copyright 2007 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# ident	"@(#)Makefile	1.2	07/01/09 SMI"
#

STF_ROOT_CONFIGURE=
STF_USER_CONFIGURE=

STF_ROOT_SETUP=
STF_USER_SETUP=

STF_ROOT_CLEANUP=cleanup
STF_USER_CLEANUP=

STF_ROOT_TESTCASES=inherit_001_pos

STF_USER_TESTCASES=

STF_DATAFILES=config001.cfg config002.cfg config003.cfg config004.cfg \
	config005.cfg config006.cfg config007.cfg config008.cfg \
	config009.cfg config010.cfg config011.cfg config012.cfg \
	config013.cfg config014.cfg config015.cfg config016.cfg \
	config017.cfg config018.cfg config019.cfg config020.cfg \
	config021.cfg config022.cfg config023.cfg config024.cfg \
	state001.cfg state002.cfg state003.cfg state004.cfg state005.cfg \
	state006.cfg state007.cfg state008.cfg state009.cfg state010.cfg \
	state011.cfg state012.cfg state013.cfg state014.cfg state015.cfg \
	state016.cfg state017.cfg state018.cfg state019.cfg state020.cfg \
	state021.cfg state022.cfg state023.cfg state024.cfg

STF_ENVFILES=inherit.cfg
STF_INCLUDES=inherit.kshlib
STF_DONTBUILDMODES=true

include ${STF_TOOLS}/Makefiles/Makefile.master
