#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#

#
# Copyright 2007 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#

STF_ROOT_CONFIGURE=
STF_USER_CONFIGURE=

STF_ROOT_SETUP=setup
STF_USER_SETUP=

STF_ROOT_CLEANUP=cleanup
STF_USER_CLEANUP=

STF_ROOT_TESTCASES=
STF_USER_TESTCASES=zfs_create_001_neg zfs_destroy_001_neg \
	zfs_unmount_001_neg zpool_add_001_neg \
	zpool_create_001_neg zpool_destroy_001_neg \
	zdb_001_neg zfs_001_neg zfs_allow_001_neg \
	zfs_clone_001_neg zfs_get_001_neg zfs_inherit_001_neg \
	zfs_mount_001_neg zfs_promote_001_neg zfs_receive_001_neg \
	zfs_rename_001_neg zfs_rollback_001_neg zfs_send_001_neg \
	zfs_set_001_neg zfs_share_001_neg zfs_snapshot_001_neg \
	zfs_upgrade_001_neg zfs_unallow_001_neg \
	zfs_unshare_001_neg zpool_001_neg zpool_attach_001_neg \
	zpool_clear_001_neg zpool_detach_001_neg \
	zpool_export_001_neg zpool_get_001_neg \
	zpool_history_001_neg zpool_import_001_neg zpool_import_002_neg \
	zpool_offline_001_neg zpool_online_001_neg \
	zpool_remove_001_neg zpool_replace_001_neg \
	zpool_scrub_001_neg zpool_set_001_neg \
	zpool_status_001_neg zpool_upgrade_001_neg


STF_EXECUTE_SUBDIRS=
STF_BUILD_SUBDIRS=

STF_ENVFILES=misc.cfg
STF_INCLUDES=

STF_DONTBUILDMODES=true

include ${STF_TOOLS}/Makefiles/Makefile.master
