#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#

#
# Copyright 2007 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#

STF_ROOT_CONFIGURE=
STF_USER_CONFIGURE=

STF_ROOT_SETUP=setup
STF_USER_SETUP=

STF_ROOT_CLEANUP=cleanup
STF_USER_CLEANUP=

STF_ROOT_TESTCASES=xattr_001_pos xattr_002_neg xattr_003_neg xattr_004_pos \
xattr_005_pos xattr_006_pos xattr_007_neg xattr_008_pos xattr_009_neg \
xattr_010_neg xattr_011_pos xattr_012_pos xattr_013_pos 
STF_USER_TESTCASES=

STF_DONTBUILDMODES=true

STF_ENVFILES=xattr_common.kshlib xattr.cfg
 
include ${STF_TOOLS}/Makefiles/Makefile.master
