#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#

#
# Copyright 2007 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#

STF_ROOT_CONFIGURE=
STF_USER_CONFIGURE=

STF_ROOT_SETUP=setup
STF_USER_SETUP=

STF_ROOT_CLEANUP=
STF_USER_CLEANUP=

STF_ROOT_TESTCASES=inuse_001_pos inuse_002_pos \
	inuse_003_pos inuse_004_pos \
	inuse_005_pos inuse_006_pos inuse_007_pos inuse_008_pos inuse_009_pos
STF_USER_TESTCASES=

STF_ENVFILES=inuse.cfg
STF_INCLUDES=
 
STF_DONTBUILDMODES=true

include $(STF_TOOLS)/Makefiles/Makefile.master
